# Generated by Django 5.2.17 on 2026-09-25 19:56

import apps.home.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='text',
            field=apps.home.fields.SummernoteTextField(verbose_name='text'),
        ),
    ]
