# Generated by Django 5.2.17 on 2026-08-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture_of_week/')),
                ('description', models.CharField(max_length=255, verbose_name='popis')),
                ('author', models.CharField(max_length=100, verbose_name='autor fotografie')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'fotografie týdne',
                'verbose_name_plural': 'fotografie týdne',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
