# Generated by Django 5.2.17 on 2026-09-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureofweek',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='picture_of_week/'),
        ),
    ]
