# Generated by Django 5.2.17 on 2026-09-25 19:22

import django_summernote.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pictureofweek_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummernoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.FileField(blank=True, editable=False, null=True, upload_to='django-summernote/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
