# Generated by Django 5.2.17 on 2026-09-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0003_summernoteattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernoteattachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='summernoteattachment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
