# Generated by Django 5.2.17 on 2026-08-26 03:54

import django.db.models.deletion
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('climbing', 'Lezení'), ('mountains', 'Hory'), ('skialpinism', 'Skialpinismus'), ('trekking', 'Trekking'), ('other_sport', 'Jiný sport'), ('kids', 'Děti'), ('pub', 'Hospoda')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'kategorie',
                'verbose_name_plural': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, verbose_name='nadpis')),
                ('text', django_summernote.fields.SummernoteTextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aktualizováno')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categories', models.ManyToManyField(blank=True, to='articles.category', verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'článek',
                'verbose_name_plural': 'články',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='popisek')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
