# Generated by Django 5.2.17 on 2026-09-25 19:28

from django.db import migrations
from django.utils.html import escape


def migrate_images_into_text(apps, schema_editor):
    """Append each article's gallery images (in order) to its text as inline
    <img> tags, before the separate ArticleImage gallery is dropped. Original
    in-text placement can't be recovered from a flat gallery, so images are
    appended at the end, preserving their existing order/captions.
    """
    Article = apps.get_model('articles', 'Article')
    ArticleImage = apps.get_model('articles', 'ArticleImage')
    for article in Article.objects.all():
        images = ArticleImage.objects.filter(article=article).order_by('order')
        fragments = []
        for image in images:
            if not image.image:
                continue
            alt = escape(image.caption) if image.caption else ''
            fragments.append(f'<p><img src="{image.image.url}" alt="{alt}"></p>')
        if fragments:
            article.text = (article.text or '') + ''.join(fragments)
            article.save(update_fields=['text'])


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(migrate_images_into_text, migrations.RunPython.noop),
    ]
