# Generated by Django 5.2.17 on 2026-09-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_migrate_images_into_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
