# Generated by Django 5.2.17 on 2026-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='titulní obrázek'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='articles/covers/'),
        ),
    ]
