# Generated by Django 5.2.17 on 2026-08-26 04:00

import django.db.models.deletion
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='název')),
                ('start_date', models.DateField(verbose_name='datum začátku')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='datum konce')),
                ('location', models.CharField(max_length=200, verbose_name='místo')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='popis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'aktivita',
                'verbose_name_plural': 'aktivity',
                'ordering': ['start_date'],
            },
        ),
    ]
