# Generated by Django 5.2.17 on 2026-09-25 19:56

import apps.home.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=apps.home.fields.SummernoteTextField(verbose_name='popis'),
        ),
    ]
